### ISSUE TITLE
DGL Version

### ISSUE THREAD

**Issue by ramkikannan** [TingJShen/Wikikg90mV2#2]
What is the version of the DGL that you used to run the dglke? I tried the latest 1.1.x version as well 0.9.x version. Both of them are giving me errors on my linux intel machine with nvidia gpus.

**Comment by TingJShen** [comment]
0.4.3 Don't use the latest version.

**Comment by TingJShen** [comment]
https://docs.dgl.ai/en/0.4.x/_modules/dgl/contrib/sampling/sampler.html

**Comment by ramkikannan** [comment]
Thank you. Just for completion of documentation, install the 0.4.3 package from https://pypi.tuna.tsinghua.edu.cn/simple/dgl/ by identifying appropriate wheel file.
